/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet_clinic;

CREATE TABLE animals(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(250),
  date_of_birth DATE,
  escape_attempts INT,
  neutered BOOLEAN,
  weight_kg DECIMAL
);

--This line is responsible for creating a new column to the animals table.
ALTER TABLE animals ADD species VARCHAR(50);

-- OWNER TABLE CREATE 
CREATE TABLE owners(
  id INT GENERATED ALWAYS AS IDENTITY, 
  full_name VARCHAR(50), 
  age INT, 
  PRIMARY KEY(id)
);

-- SPECIES TABLE CREATE
CREATE TABLE species(
  id INT GENERATED ALWAYS AS IDENTITY, 
  name VARCHAR(50), 
  PRIMARY KEY(id)
);

-- ALTER animals TABLE TO CONTAIN SPECIES_ID
ALTER TABLE animals ADD COLUMN species_id INT, 
ADD CONSTRAINT f_species_id  FOREIGN KEY (species_id) REFERENCES species(id);

-- ALTER animals TABLE TO CONTAIN OWNER_ID
ALTER TABLE animals ADD COLUMN owners_id INT, 
ADD CONSTRAINT f_owners_id FOREIGN KEY (owners_id) REFERENCES owners(id);

-- CREATE VETS TABLE
CREATE TABLE vets (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, age INT NOT NULL, date_of_graduation DATE NOT NULL);

-- CREATE TABLE SPECIALIZATION
CREATE TABLE specializations (species_id INT NOT NULL, vets_id INT NOT NULL, 
CONSTRAINT f_species FOREIGN KEY(species_id) REFERENCES species(id) ON DELETE CASCADE, 
CONSTRAINT f_vets FOREIGN KEY(vets_id) REFERENCES vets(id), PRIMARY KEY(species_id,vets_id)
); 

-- CREATE TABLE VISITS
CREATE TABLE visits (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, animal_id INT NOT NULL, vet_id INT NOT NULL, date_of_visit DATE NOT NULL, 
CONSTRAINT fk_animals FOREIGN KEY (animal_id) REFERENCES animals(id), 
CONSTRAINT fk_vets FOREIGN KEY (vet_id) REFERENCES vets(id)
);

ALTER TABLE owners ADD COLUMN email VARCHAR(120);

DROP TABLE visits;

CREATE TABLE visits(
    id INT GENERATED ALWAYS AS IDENTITY,
    animal_id INT REFERENCES animals(id),
    vet_id INT REFERENCES vets(id),
    date_of_visit DATE,
    PRIMARY KEY(id)
);

CREATE INDEX animal_index ON visits(animal_id);

CREATE INDEX vets_index ON visits(vet_id);

CREATE INDEX email_check ON owners(email);
